package com.movie.filmtube.data;

import com.google.gson.annotations.SerializedName;
import com.movie.filmtube.utils.ServiceConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {
	@SerializedName(ServiceConfig.TAG_UNKNOWN)
	private Long id;
	@SerializedName(ServiceConfig.TAG_CATEGORY_NAME)
	private String name;
	@SerializedName(ServiceConfig.TAG_ID)
	private Long serverId;

	public Category() {
	}

	public Category(Long id) {
		this.id = id;
	}

	public Category(Long id, String name, Long serverId) {
		this.id = id;
		this.name = name;
		this.serverId = serverId;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Long getServerId() {
		return serverId;
	}

	public void setServerId(Long serverId) {
		this.serverId = serverId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Category [id=" + id + ", name=" + name + ", serverId="
				+ serverId + "]";
	}

}
